### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by recklessbeav** [okaystephen/stsweng-kubernetes#100]
Name: Footer
Date: January 27, 2020
Description: The footer is not on the bottom of the page 
Steps to Reproduce:
1. localhost:3001
2. Go to Doctors Directory
3. Filter Dental Medicine as the Specialization 
Expected Result: The footer should be on the bottom page and an extra space shouldn't be seen 
Actual Result:
![image](https://user-images.githubusercontent.com/61379865/106010245-3147ae00-60f4-11eb-82eb-6bc1c60abd07.png)

**Comment by iravillanuevaa** [comment]
fixed!
![image](https://user-images.githubusercontent.com/44962560/106021782-1ed37180-6100-11eb-94ef-9108fb8478e8.png)
