### ISSUE TITLE
Health Programs Description

### ISSUE THREAD

**Issue by recklessbeav** [okaystephen/stsweng-kubernetes#102]
Name: Health Program Page Description
Date: January 27, 2020
Description: "Insert Caption Here" is not professional
Steps to Reproduce:
1. localhost:3001
2. Go to Health Programs 
Expected Result:

Write this instead:

Dolomed offers available health programs. These programs aim to aim to prevent or control disease, injury, disability, and death. It also offers a comprehensive health initiative designed to maintain or improve well-being through proper diet, exercise, stress management, and illness prevention. Register now!

Actual Result:
![image](https://user-images.githubusercontent.com/61379865/106012109-0d856780-60f6-11eb-87b7-d59e188e60b9.png)

**Comment by recklessbeav** [comment]
please also add this description on the admin side thank you

**Comment by iravillanuevaa** [comment]
fixed! 
![image](https://user-images.githubusercontent.com/44962560/106022251-9a352300-6100-11eb-9f86-e7dec64d6bfa.png)
