### ISSUE TITLE
Register in Health Program

### ISSUE THREAD

**Issue by recklessbeav** [okaystephen/stsweng-kubernetes#103]
Name: Register in Health Program without a reason
Date: January 28, 2020
Description: The error message says "Registration failed: You tried submitting an empty field. Please try again."
Steps to Reproduce:
1. localhost:3001
2. Sign In as a user
3. Go to Health Program
4. Register to a Program
5. Purposely Register without a reason on the text box
Expected Result: Replace it with "Registration failed: You tried to register to a program without a reason. Please try again."
Actual Result:
![image](https://user-images.githubusercontent.com/61379865/106109800-e6c24200-6184-11eb-97d0-298971bf775d.png)

**Comment by iravillanuevaa** [comment]
Fixed! Replaced the error message with "Registration failed: You tried to register to a program without a reason. Please try again."
![image](https://user-images.githubusercontent.com/44962560/106151083-f490bb00-61b6-11eb-8397-caf61c56646f.png)
