### ISSUE TITLE
Footer: No underlines when hovering over text in some pages

### ISSUE THREAD

**Issue by alyssonsilverio** [okaystephen/stsweng-kubernetes#105]
Title: No underlines when hovering over text in some pages
Date: 1/28/2021
Description: Hovering over text in footer only shows an underline in the landing page.

Steps to Reproduce:
1. localhost:3001
2. Hover over About/Health Programs/Doctors in the footer

Expected Result: Underline will appear for all pages
Actual Result: Underline only appears in the landing page

![image](https://user-images.githubusercontent.com/74369428/106148520-18063680-61b4-11eb-8a3e-65d1c5568608.png)
![image](https://user-images.githubusercontent.com/74369428/106148541-1f2d4480-61b4-11eb-92f1-032ff70b90fd.png)

**Comment by okaystephen** [comment]
Appears on other pages now
![Screen Shot 2021-01-28 at 10 57 04 PM](https://user-images.githubusercontent.com/44962445/106156203-37a15d00-61bc-11eb-8835-abce5a93a1f7.png)
![Screen Shot 2021-01-28 at 10 57 14 PM](https://user-images.githubusercontent.com/44962445/106156206-3839f380-61bc-11eb-8210-a6bb254c169d.png)
