### ISSUE TITLE
UI: Remove side navigation bar

### ISSUE THREAD

**Issue by alyssonsilverio** [okaystephen/stsweng-kubernetes#106]
Title: Remove side navigation bar
Date: 1/28/2021
Description: In the Dashboard/User Profile, remove the side navigation bar

Steps to Reproduce:
1. localhost:3001
2. Log in
3. Go to Dashboard

![image](https://user-images.githubusercontent.com/74369428/106148687-526fd380-61b4-11eb-9e30-ae16c2fc6f2a.png)

**Comment by okaystephen** [comment]
![Screen Shot 2021-01-29 at 1 00 56 AM](https://user-images.githubusercontent.com/44962445/106172241-8d323580-61cd-11eb-885f-67d700518fa6.png)
![Screen Shot 2021-01-29 at 1 01 01 AM](https://user-images.githubusercontent.com/44962445/106172244-8dcacc00-61cd-11eb-8ff2-5ad2ac2d4192.png)
![Screen Shot 2021-01-29 at 1 01 07 AM](https://user-images.githubusercontent.com/44962445/106172247-8efbf900-61cd-11eb-9562-2dda0df9c6ec.png)
![Screen Shot 2021-01-29 at 1 01 11 AM](https://user-images.githubusercontent.com/44962445/106172249-902d2600-61cd-11eb-93a5-6b47b2c294ea.png)
