### ISSUE TITLE
Set an appointment: Time

### ISSUE THREAD

**Issue by alyssonsilverio** [okaystephen/stsweng-kubernetes#43]
Name: Leaving time blank and pressing Submit
Date: Dec. 11, 2020
Description: Leaving time blank and pressing Submit sets an appointment at 12:00AM

Steps to Reproduce:

1. localhost:3001
2. Log In
3. Set an Appointment
4. Leave Time blank and press Submit

Expected Result: Error message
Actual Result: Appointment is set at 12:00AM

**Comment by okaystephen** [comment]
Added validators
![Screen Shot 2020-12-11 at 11 41 54 PM](https://user-images.githubusercontent.com/44962445/101927090-0a4e1f00-3c0f-11eb-93ad-d6c9d01f78c1.png)
![Screen Shot 2020-12-11 at 11 42 08 PM](https://user-images.githubusercontent.com/44962445/101927108-0fab6980-3c0f-11eb-9480-b7001e405bf5.png)
