### ISSUE TITLE
Set an appointment: Doctor

### ISSUE THREAD

**Issue by alyssonsilverio** [okaystephen/stsweng-kubernetes#44]
Name: Selecting no doctor and pressing Submit
Date: Dec. 11, 2020
Description: Selecting no doctor and pressing Submit causes the website to crash

Steps to Reproduce:
1. localhost:3001
2. Log In
3. Set an Appointment
4. Do not select a doctor and press Submit

Expected Result: Error message
Actual Result: Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters

**Comment by okaystephen** [comment]
Added validators
![Screen Shot 2020-12-11 at 11 41 54 PM](https://user-images.githubusercontent.com/44962445/101927213-2d78ce80-3c0f-11eb-91f6-7890b6a26a4b.png)
![Screen Shot 2020-12-11 at 11 42 08 PM](https://user-images.githubusercontent.com/44962445/101927218-2f429200-3c0f-11eb-9b79-84d4fb409699.png)
