### ISSUE TITLE
Set an appointment: Past Date

### ISSUE THREAD

**Issue by alyssonsilverio** [okaystephen/stsweng-kubernetes#45]
Name: Entering a date in the past
Date: Dec. 11, 2020
Description: Entering a date in the past and pressing Submit still allows the appointment to be set

Steps to Reproduce:

1. localhost:3001
2. Log in
3. Appointments Page
4. Enter 4/18/2001 in the Date and press "Submit"

Expected Result: Error message
Actual Result: Appointment is still set

**Comment by okaystephen** [comment]
Cannot enter past date anymore
![Screen Shot 2020-12-12 at 12 13 01 AM](https://user-images.githubusercontent.com/44962445/101927007-edb1e700-3c0e-11eb-85c3-7ff1ce0d78c3.png)
![Screen Shot 2020-12-12 at 12 13 41 AM](https://user-images.githubusercontent.com/44962445/101927013-ef7baa80-3c0e-11eb-82a6-7b10af408637.png)
