### ISSUE TITLE
Set an appointment: Reason for appointment

### ISSUE THREAD

**Issue by alyssonsilverio** [okaystephen/stsweng-kubernetes#46]
Name: Leaving reason for appointment blank and pressing Submit
Date: Dec. 11, 2020
Description: Leaving reason for appointment blank and pressing Submit causes the website to load infinitely

Steps to Reproduce:

1. localhost:3001
2. Log In
3. Set an Appointment
4. Leave reason for appointment blank and press Submit

Expected Result: Error message
Actual Result: Website loads infinitely

**Comment by okaystephen** [comment]
Added validators
![Screen Shot 2020-12-11 at 11 41 54 PM](https://user-images.githubusercontent.com/44962445/101926310-fa820b00-3c0d-11eb-9632-49ef8952c4f9.png)
![Screen Shot 2020-12-11 at 11 42 08 PM](https://user-images.githubusercontent.com/44962445/101926321-feae2880-3c0d-11eb-99b3-a16df0310df5.png)
