### ISSUE TITLE
Set an appointment: Doctor not available

### ISSUE THREAD

**Issue by alyssonsilverio** [okaystephen/stsweng-kubernetes#56]
Name: Set an appointment: Doctor not available
Date: Dec. 11, 2020
Description: It is possible to set an appointment that does not match the doctor's available schedule

Steps to Reproduce:

1. localhost:3001
2. Log In
3. Set an Appointment
4. Choose any doctor and set an appointment at 3:00AM

Expected Result: Error message
Actual Result: Appointment is still set

**Comment by okaystephen** [comment]
Date and time validators are working now.
![Screen Shot 2020-12-30 at 1 13 11 AM](https://user-images.githubusercontent.com/44962445/103301465-77015000-4a3c-11eb-8ae7-beb58febd71a.png)
![Screen Shot 2020-12-30 at 1 13 22 AM](https://user-images.githubusercontent.com/44962445/103301467-7799e680-4a3c-11eb-88f9-bf838e657cc1.png)
![Screen Shot 2020-12-30 at 1 13 29 AM](https://user-images.githubusercontent.com/44962445/103301473-7963aa00-4a3c-11eb-86bb-40488841eab7.png)
![Screen Shot 2020-12-30 at 1 14 31 AM](https://user-images.githubusercontent.com/44962445/103301475-79fc4080-4a3c-11eb-94aa-c818af634e55.png)
![Screen Shot 2020-12-30 at 1 14 51 AM](https://user-images.githubusercontent.com/44962445/103301480-7c5e9a80-4a3c-11eb-8f4a-93a39103c1c4.png)
