### ISSUE TITLE
Set an appointment: Can set multiple appointments at the same date and time

### ISSUE THREAD

**Issue by alyssonsilverio** [okaystephen/stsweng-kubernetes#65]
Name: Set an appointment: Can set multiple appointments at the same date and time
Date: Dec. 16, 2020
Description: It is possible to set multiple appointments at the same date and time

Steps to Reproduce:

1. localhost:3001
2. Log In
3. Set an Appointment
4. Set two appointments that land on the same time and date

Expected Result: Error message
Actual Result: Appointments are still set

**Comment by okaystephen** [comment]
There's an error message now
![Screen Shot 2020-12-30 at 12 45 40 AM](https://user-images.githubusercontent.com/44962445/103299890-8ed6d500-4a38-11eb-9be9-613a35181695.png)
![Screen Shot 2020-12-30 at 12 45 59 AM](https://user-images.githubusercontent.com/44962445/103299894-90080200-4a38-11eb-9cfc-12c4110fd7e6.png)
