### ISSUE TITLE
Landing page: Login from "Book an appointment now"

### ISSUE THREAD

**Issue by alyssonsilverio** [okaystephen/stsweng-kubernetes#73]
Name: Login from "Book an appointment now"
Date: Jan. 09, 2021
Description: The login pop-up still appears even though the user is already logged in.

1. localhost:3001
2. Login
3. Go back to landing page
4. Press "book an appointment now"

Expected Result: Redirected to set an appointment page
Actual Result: Login pop-up appears

![image](https://user-images.githubusercontent.com/74369428/104091057-ecc7b000-52b5-11eb-88a3-e7f7b68eabfc.png)

**Comment by okaystephen** [comment]
Fixed now
![Screen Shot 2021-01-09 at 8 53 57 PM](https://user-images.githubusercontent.com/44962445/104092166-1cc68180-52bd-11eb-8330-35d2911f7494.png)
![Screen Shot 2021-01-09 at 8 54 00 PM](https://user-images.githubusercontent.com/44962445/104092168-1df7ae80-52bd-11eb-940f-e6fc15bc69a1.png)
