### ISSUE TITLE
Add Doctor appointment - End time earlier than start time

### ISSUE THREAD

**Issue by alyssonsilverio** [okaystephen/stsweng-kubernetes#86]
Title:  End time earlier than start time
Date: Jan 18, 2021
Description: It is possible to set the schedule of a doctor with the end time being earlier than the start time

Steps to Reproduce:
1. localhost:3001
2. Login admin account
3. Go to Doctors
4. Press Add a Doctor
5. Enter a schedule wherein the end time is earlier (ex. Start time: 12:00PM, end time: 9:00AM)

Expected Result: Error message
Actual result: Still added to directory
![image](https://user-images.githubusercontent.com/74369428/104865096-05029380-5976-11eb-8e22-9d2b21de43e7.png)

**Comment by okaystephen** [comment]
Fixed
![Screen Shot 2021-01-20 at 2 20 58 AM](https://user-images.githubusercontent.com/44962445/105076835-9123d080-5ac6-11eb-9ff9-b0131e9eb939.png)
![Screen Shot 2021-01-20 at 2 21 04 AM](https://user-images.githubusercontent.com/44962445/105076839-9254fd80-5ac6-11eb-9506-ddcac7a04830.png)
![Screen Shot 2021-01-20 at 2 21 47 AM](https://user-images.githubusercontent.com/44962445/105076843-93862a80-5ac6-11eb-97fb-6785e7c4d62e.png)
![Screen Shot 2021-01-20 at 2 21 50 AM](https://user-images.githubusercontent.com/44962445/105076845-941ec100-5ac6-11eb-9b1a-c03bf6dc67f4.png)
