### ISSUE TITLE
Record of appointments: Deleting from appointment records

### ISSUE THREAD

**Issue by alyssonsilverio** [okaystephen/stsweng-kubernetes#93]
Name: Record of appointments: Deleting from appointment records
Date: Jan 25, 2021
Description: Edit icon instead of remove icon, confirmation pop-up lacks information, and pressing confirm causes the page to buffer infinitely

1. Login admin account
2. Go to Appointments
3. Enter 12/17/2020
4. Attempt to remove a record

![image](https://user-images.githubusercontent.com/74369428/105700021-39142080-5f43-11eb-96a2-a0b4ebbd89e1.png)
![image](https://user-images.githubusercontent.com/74369428/105700231-898b7e00-5f43-11eb-8ad4-0ab6182134b8.png)

**Comment by okaystephen** [comment]
Added the feature now
![Screen Shot 2021-01-26 at 2 50 30 AM](https://user-images.githubusercontent.com/44962445/105751696-58ca3980-5f81-11eb-9744-fea4724689f3.png)
![Screen Shot 2021-01-26 at 2 50 35 AM](https://user-images.githubusercontent.com/44962445/105751705-5b2c9380-5f81-11eb-9efb-a04f5d3890be.png)
![Screen Shot 2021-01-26 at 2 50 37 AM](https://user-images.githubusercontent.com/44962445/105751724-5ff14780-5f81-11eb-8034-14d175f5bb92.png)
