### ISSUE TITLE
Landing page: Admin can register in health programs

### ISSUE THREAD

**Issue by alyssonsilverio** [okaystephen/stsweng-kubernetes#98]
Name: Admin can register in health programs
Date: Jan 27, 2021
Description: Pressing "Health Programs" from the landing page while logged in the admin account redirects the admin to the Health Programs page meant for users instead of the admin Health Programs page.

1. localhost:3001
2. Log In admin account
3. Press "Health Programs"

![image](https://user-images.githubusercontent.com/74369428/106000418-c1342a80-60e9-11eb-8f45-71468c9be8f9.png)

**Comment by iravillanuevaa** [comment]
fixed!
![image](https://user-images.githubusercontent.com/44962560/106004845-94364680-60ee-11eb-9e02-ebb7991c78a3.png)
